In [3]:
import numpy as np

## Random number from a Standard Normal Distribution
Use the `rand` function to generate numbers from the standard normal distibition $N(0,1)$

In [14]:
# Random numbers from a statard normal distribution 

rand_num = np.random.randn(10)
rand_num

array([ 1.03834458, -1.17017494,  0.75666295,  0.41393397, -2.48587658,
       -1.75889766, -0.30184055,  0.70666215, -0.10206799,  0.61295805])

## Random Integer from Range
We can generate a an integer from within a range using the `integers` method in `default_rng()`. Here we specify the start and end of the rang - both inclusive - and the number of draws we want from within this range.  

In [13]:
# Random number within a range 
# Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive)

rng = np.random.default_rng()
a = rng.integers(1,6,10)
a

array([5, 5, 4, 3, 1, 2, 4, 5, 4, 1])

# Random Floas 0-1
Generate a random value inbeteen 0 and 1. Will be helpfull for gerating random probabilities.

In [10]:
# Retrun value betwen 0 and 1
## Return random floats in the half-open interval [0.0, 1.0).

x = np.random.random(10)
x

array([0.62887944, 0.43428408, 0.74646825, 0.09828681, 0.39215318,
       0.07781022, 0.22060355, 0.15091109, 0.93144916, 0.91207824])

# Random Choice
Choose at ramndom from a list of items/catagories in a list. 

In [12]:
# random Choice 

options = ['A', 'B', 'C']
x = np.random.choice(options, 10)
x

array(['C', 'C', 'B', 'A', 'A', 'A', 'B', 'C', 'C', 'B'], dtype='<U1')

# Random Shuffle 
If we want to shuffel the order oif an exising catagoery top randomise we can also do taht using the `shuffle` method in the `default_range()` function. 

In [19]:
rng = np.random.default_rng()
a = ['a', 'b', 'c', 'd', 'e']
rng.shuffle(a)
a

['b', 'c', 'e', 'a', 'd']